# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNo', models.IntegerField()),
                ('cardnumber', models.CharField(max_length=14)),
                ('requestCount', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'bookRequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('barcode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dateaccessioned', models.DateField()),
                ('title', models.CharField(max_length=105)),
                ('author', models.CharField(max_length=43)),
                ('Subject', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='books_db',
            fields=[
                ('barcode', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dateaccessioned', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=37)),
                ('Subject', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'books_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bt_map',
            fields=[
                ('barcode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bt_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='libraryRecommendation',
            fields=[
                ('srNo', models.AutoField(primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('requestCount', models.IntegerField()),
            ],
            options={
                'db_table': 'libraryRecommendation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('cardnumber', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=9)),
                ('rating', models.IntegerField()),
                ('valid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('DATE', models.DateField()),
                ('barcode', models.CharField(max_length=9)),
                ('cardnumber', models.CharField(max_length=14)),
                ('Name', models.CharField(max_length=39)),
                ('branchcode', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('SrNo', models.IntegerField()),
                ('barcode_no', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Roll_No', models.IntegerField()),
                ('Name', models.CharField(max_length=35)),
                ('Gender', models.CharField(max_length=6)),
                ('Class', models.CharField(max_length=28)),
                ('Student_EMail', models.CharField(max_length=37)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
