# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=14)),
                ('barcode', models.CharField(max_length=9)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
