# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-29 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedBooks',
            fields=[
                ('barcode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dateaccessioned', models.DateField()),
                ('title', models.CharField(max_length=105)),
                ('author', models.CharField(max_length=43)),
                ('Subject', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'deletedBooks',
                'managed': False,
            },
        ),
    ]
