# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('barcode', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dateaccessioned', models.DateField()),
                ('title', models.CharField(max_length=105)),
                ('author', models.CharField(max_length=43)),
                ('Subject', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='books_db',
            fields=[
                ('barcode', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dateaccessioned', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=37)),
                ('Subject', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'books_db',
                'managed': False,
            },
        ),
    ]
