# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_books_books_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='bt_map',
            fields=[
                ('barcode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bt_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('SrNo', models.IntegerField()),
                ('barcode_no', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Roll_No', models.IntegerField()),
                ('Name', models.CharField(max_length=35)),
                ('Gender', models.CharField(max_length=6)),
                ('Class', models.CharField(max_length=28)),
                ('Student_EMail', models.CharField(max_length=37)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
