# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryRecommendation',
            fields=[
                ('srNO', models.IntegerField(primary_key=True, serialize=False)),
                ('bookTitle', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('requestCount', models.IntegerField()),
            ],
            options={
                'db_table': 'libraryRecommendation',
                'managed': False,
            },
        ),
    ]
